### PR TITLE
Fix/1468 automapping covariates issue

### LINKED ISSUE #1468: Automapping on UI mapping page causes covariates to disappear

### PR DESCRIPTION
**Pull request by kalitopix**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](../CONTRIBUTING.md)
- [] If your PR contains DB doc changes have you made an API migration and a localDB migration if necessary?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
- [] Tests for the changes have been added (for bug fixes / features)
- [] Passes e2e testing
- [] Passes lint
- [] Docs have been added / updated if necessary (for bug fixes / features)

* **What kind of change does this PR introduce?**
Bug fix

* **What is the current behavior?** 
closes #1468 

* **Does this PR introduce a breaking change?**
No

### CODE REVIEW

File: packages/coinstac-ui/app/render/components/maps/fields/maps-csv-field.jsx [hunk 1]
```diff
@@ -233,8 +233,10 @@ class MapsCsvField extends React.Component {
         return acc;
       }, {});
 
+      const mapColumns = map.map(elem => elem.column);
+
       this.setState(prevState => ({
-        remainingHeader: prevState.remainingHeader.filter(column => map.includes(column)),
```
Comment (dylanmartin) [inline packages/coinstac-ui/app/render/components/maps/fields/maps-csv-field.jsx:237]: It looks like this filter didn't work to begin with because `map` is an array of objects and `.includes` is only checking for column names. Meaning it would always be false.

**Review by dylanmartin — APPROVED** [review]
